apiVersion: v1
data:
  backend-prod.yaml: |-
    ---
    name: "Проблема с бекендом в кластере YC-CPM (PROD)"
    type: any
    index: filebeat-*
    filter:
    - query:
        query_string:
          query: "kubernetes.namespace: *-prod AND (json.severity:(ERROR OR CRITICAL) OR json.level_name:(ERROR OR CRITICAL))"
    alert:
    - "rob"
    include: ["json.message", "json.data", "kubernetes.labels.app", "_id", "_index"]
    alert_missing_value: ""
    alert_subject: "**`{0}`**"
    alert_subject_args: ["kubernetes.labels.app"]
    max_query_size: 10
    alert_text: |+
        {0}
        ```
        {1}

        {3}
        ```

        **[Подробности здесь](https://logs.online.olimpiada.ru/app/kibana#/discover?_g=%28refreshInterval:%28pause:!t,value:0%29,time:%28from:now-1d,to:now%29%29&=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28query_string:%28analyze_wildcard:!t,query:'_id:{2}'%29%29%29&_a=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28language:kuery,query:%27_id:%22{2}%22%27%29,sort:!%28!%28'@timestamp',desc%29%29%29)
    alert_text_args: ["breakline", "message", "_id"]
    alert_text_type: alert_text_only
    alert: "elastalert_modules.rob.RobAlerter"
    rob_url: "https://rob.sirius.online/message/logs_cpm_prod_alert"
    rob_token: "eyJhbGciOiJQUzUxMiJ9.eyJlbWFpbCI6ImdpdGxhYkBzaXJpdXMub25saW5lIiwicm9sZXMiOltdLCJtaWRkbGVOYW1lIjoiIiwibGFzdE5hbWUiOiIiLCJmaXJzdE5hbWUiOiIiLCJpZCI6IjAiLCJwYXJlbnRDb2RlIjpudWxsfQ.4wElX1AAbYchLsUUN8DFNJb3THG7XsURqzYpv98hvrGVZaIxQpmjrS8bIVfcgkewRlRyhBoxamxAqsbNMpBj359FgLdHiOCpst-HPM-hSClNyIEdeJYUDQXkKBL4IIkvwZ4etXwzGhubFtD44unZxgEqzcCDc3ShCts7l0OAxa3LvTue_f_JhxpUYSDQn84jnswEUKvcWGpZ5PcleptbvIM7_yG8h9RxulvXxgckDO5wWqRECcJIqfWMR57xI0aeTgZa1Fh2s7Ljtd7jgtg8nINB4X1FCm11w5MfKcKm-SJEnEcvy8VXDd3srw7iD30KYcQVa2VnVbGUKREcU9IEmg"
    kibana_url: "https://logs.online.olimpiada.ru"
  elastic.yaml: |-
    ---
    name: "Проблема с ELASTIC в CPM"
    type: frequency
    num_events: 3
    timeframe:
      minutes: 2
    index: filebeat-*
    filter:
    - query:
        query_string:
          query: "kubernetes.namespace: logging AND message: *Exception* AND kubernetes.labels.app: elastic*"
    alert:
    - "rob"
    include: ["kubernetes.labels","kubernetes.container.name", "message", "_id"]
    alert_missing_value: ""
    alert_subject: "**`{0}`**"
    alert_subject_args: ["kubernetes.labels.app"]
    alert_text: |
        {0}
        ```
        {1}
        ```

        **[Подробности здесь](https://logs.online.olimpiada.ru/app/kibana#/discover?_g=%28refreshInterval:%28pause:!t,value:0%29,time:%28from:now-1d,to:now%29%29&=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28query_string:%28analyze_wildcard:!t,query:'_id:{2}'%29%29%29&_a=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28language:kuery,query:%27_id:%22{2}%22%27%29,sort:!%28!%28'@timestamp',desc%29%29%29)**
    alert_text_args: ["breakline", "message", "_id"]
    alert_text_type: alert_text_only
    alert: "elastalert_modules.rob.RobAlerter"
    rob_url: "https://rob.sirius.online/message/logs_cpm_prod_alert"
    rob_token: "eyJhbGciOiJQUzUxMiJ9.eyJlbWFpbCI6ImdpdGxhYkBzaXJpdXMub25saW5lIiwicm9sZXMiOltdLCJtaWRkbGVOYW1lIjoiIiwibGFzdE5hbWUiOiIiLCJmaXJzdE5hbWUiOiIiLCJpZCI6IjAiLCJwYXJlbnRDb2RlIjpudWxsfQ.4wElX1AAbYchLsUUN8DFNJb3THG7XsURqzYpv98hvrGVZaIxQpmjrS8bIVfcgkewRlRyhBoxamxAqsbNMpBj359FgLdHiOCpst-HPM-hSClNyIEdeJYUDQXkKBL4IIkvwZ4etXwzGhubFtD44unZxgEqzcCDc3ShCts7l0OAxa3LvTue_f_JhxpUYSDQn84jnswEUKvcWGpZ5PcleptbvIM7_yG8h9RxulvXxgckDO5wWqRECcJIqfWMR57xI0aeTgZa1Fh2s7Ljtd7jgtg8nINB4X1FCm11w5MfKcKm-SJEnEcvy8VXDd3srw7iD30KYcQVa2VnVbGUKREcU9IEmg"
    kibana_url: "https://logs.online.olimpiada.ru"
  herald.yaml: "---\nname: \"Проблема с HERALD в кластере YC-CPM\"\ntype: any\nindex:
    filebeat-*\nfilter:\n- query:\n    query_string:\n      query: \"kubernetes.container.name:herald
    AND json.level:error\"\nalert:\n- \"herald\"\ninclude: [\"json.msg\", \"kubernetes.labels.app\",
    \"_id\", \"_index\"]\nalert_missing_value: \"\"\nalert_subject: \"Логи, {0}, кластер
    YC-CPM (PROD)\"\nalert_subject_args: [\"kubernetes.labels.app\"]\nalert_text:
    |+\n    {0}\n    ```\n    {1}\n    ```\n    \n    **[Подробности здесь](https://logs.online.olimpiada.ru/app/kibana#/discover?_g=%28refreshInterval:%28pause:!t,value:0%29,time:%28from:now-1d,to:now%29%29&=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28query_string:%28analyze_wildcard:!t,query:'_id:{2}'%29%29%29&_a=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28language:kuery,query:%27_id:%22{2}%22%27%29,sort:!%28!%28'@timestamp',desc%29%29%29)**\nalert_text_args:
    [\"breakline\", \"json.msg\", \"_id\"]\nalert_text_type: alert_text_only\nalert:
    \"elastalert_modules.herald.HeraldAlerter\"\nherald_url: \"https://herald.online.olimpiada.ru/api/v1/messages/logs_cpm_prod_alert\"\nherald_token:
    \"eyJhbGciOiJQUzUxMiJ9.eyJlbWFpbCI6ImdpdGxhYkBzaXJpdXMub25saW5lIiwicm9sZXMiOltdLCJtaWRkbGVOYW1lIjoiIiwibGFzdE5hbWUiOiIiLCJmaXJzdE5hbWUiOiIiLCJpZCI6IjAiLCJwYXJlbnRDb2RlIjpudWxsfQ.4wElX1AAbYchLsUUN8DFNJb3THG7XsURqzYpv98hvrGVZaIxQpmjrS8bIVfcgkewRlRyhBoxamxAqsbNMpBj359FgLdHiOCpst-HPM-hSClNyIEdeJYUDQXkKBL4IIkvwZ4etXwzGhubFtD44unZxgEqzcCDc3ShCts7l0OAxa3LvTue_f_JhxpUYSDQn84jnswEUKvcWGpZ5PcleptbvIM7_yG8h9RxulvXxgckDO5wWqRECcJIqfWMR57xI0aeTgZa1Fh2s7Ljtd7jgtg8nINB4X1FCm11w5MfKcKm-SJEnEcvy8VXDd3srw7iD30KYcQVa2VnVbGUKREcU9IEmg\""
kind: ConfigMap
metadata:
  labels:
    app: elastalert
    release: elastalert
  name: rules
