apiVersion: v1
data:
  elastalert_config: |-
    ---
    rules_folder: /opt/rules
    max_scrolling_count: 990
    scan_subdirectories: false
    run_every:
      minutes: 1
    buffer_time:
      minutes: 5
    es_host: elasticsearch-master.logging.svc
    es_port: 9200
    writeback_index: elastalert_status
    use_ssl: False
    verify_certs: True
    alert_time_limit:
      minutes: 60
kind: ConfigMap
metadata:
  labels:
    app: elastalert
    release: elastalert
  name: config