nodeSelector:
  nodeRole: monitoring

rules:
  backend-dev.yaml: |-
    name: "Проблема с бекендом в кластере SIRIUS (DEV)"
    type: any
    index: filebeat-*
    filter:
    - query:
        query_string:
          query: "kubernetes.namespace: *-dev AND (json.severity:(ERROR OR CRITICAL) OR json.level_name:(ERROR OR CRITICAL))"
    alert:
    - "rob"
    include: ["json.message", "json.data", "kubernetes.labels.app", "_id", "_index"]
    max_query_size: 10
    alert_missing_value: ""
    alert_subject: "**`{0}`**"
    alert_subject_args: ["kubernetes.labels.app"]
    alert_text: |+
        {0}
        ```
        {1}

        {3}
        ```

        **[Подробности здесь](https://logs.sirius.online/app/kibana#/discover?_g=%28refreshInterval:%28pause:!t,value:0%29,time:%28from:now-1d,to:now%29%29&=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28query_string:%28analyze_wildcard:!t,query:'_id:{2}'%29%29%29&_a=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28language:kuery,query:%27_id:%22{2}%22%27%29,sort:!%28!%28'@timestamp',desc%29%29%29)**
    alert_text_args: ["breakline", "json.message", "_id", "json.data"]
    alert_text_type: alert_text_only
    alert: "elastalert_modules.rob.RobAlerter"
    rob_url: "https://rob.sirius.online/message/logs_dev_alert"
    rob_token: "eyJhbGciOiJQUzUxMiJ9.eyJlbWFpbCI6ImdpdGxhYkBzaXJpdXMub25saW5lIiwicm9sZXMiOltdLCJtaWRkbGVOYW1lIjoiIiwibGFzdE5hbWUiOiIiLCJmaXJzdE5hbWUiOiIiLCJpZCI6IjAiLCJwYXJlbnRDb2RlIjpudWxsfQ.4wElX1AAbYchLsUUN8DFNJb3THG7XsURqzYpv98hvrGVZaIxQpmjrS8bIVfcgkewRlRyhBoxamxAqsbNMpBj359FgLdHiOCpst-HPM-hSClNyIEdeJYUDQXkKBL4IIkvwZ4etXwzGhubFtD44unZxgEqzcCDc3ShCts7l0OAxa3LvTue_f_JhxpUYSDQn84jnswEUKvcWGpZ5PcleptbvIM7_yG8h9RxulvXxgckDO5wWqRECcJIqfWMR57xI0aeTgZa1Fh2s7Ljtd7jgtg8nINB4X1FCm11w5MfKcKm-SJEnEcvy8VXDd3srw7iD30KYcQVa2VnVbGUKREcU9IEmg"
    kibana_url: "https://logs.sirius.online"
  backend-prod.yaml: |-
    ---
    name: "Проблема с бекендом в кластере SIRIUS (PROD)"
    type: any
    index: filebeat-*
    filter:
    - query:
        query_string:
          query: "kubernetes.namespace: *-prod AND (json.severity:(ERROR OR CRITICAL) OR json.level_name:(ERROR OR CRITICAL))"
    alert:
    - "rob"
    include: ["json.message", "json.data", "kubernetes.labels.app", "_id", "_index"]
    alert_missing_value: ""
    alert_subject: "**`{0}`**"
    alert_subject_args: ["kubernetes.labels.app"]
    max_query_size: 10
    alert_text: |+
        {0}
        ```
        {1}

        {3}
        ```

        **[Подробности здесь](https://logs.sirius.online/app/kibana#/discover?_g=%28refreshInterval:%28pause:!t,value:0%29,time:%28from:now-1d,to:now%29%29&=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28query_string:%28analyze_wildcard:!t,query:'_id:{2}'%29%29%29&_a=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28language:kuery,query:%27_id:%22{2}%22%27%29,sort:!%28!%28'@timestamp',desc%29%29%29)**
    alert_text_args: ["breakline", "json.message", "_id", "json.data"]
    alert_text_type: alert_text_only
    alert: "elastalert_modules.rob.RobAlerter"
    rob_url: "https://rob.sirius.online/message/logs_prod_alert"
    rob_token: "eyJhbGciOiJQUzUxMiJ9.eyJlbWFpbCI6ImdpdGxhYkBzaXJpdXMub25saW5lIiwicm9sZXMiOltdLCJtaWRkbGVOYW1lIjoiIiwibGFzdE5hbWUiOiIiLCJmaXJzdE5hbWUiOiIiLCJpZCI6IjAiLCJwYXJlbnRDb2RlIjpudWxsfQ.4wElX1AAbYchLsUUN8DFNJb3THG7XsURqzYpv98hvrGVZaIxQpmjrS8bIVfcgkewRlRyhBoxamxAqsbNMpBj359FgLdHiOCpst-HPM-hSClNyIEdeJYUDQXkKBL4IIkvwZ4etXwzGhubFtD44unZxgEqzcCDc3ShCts7l0OAxa3LvTue_f_JhxpUYSDQn84jnswEUKvcWGpZ5PcleptbvIM7_yG8h9RxulvXxgckDO5wWqRECcJIqfWMR57xI0aeTgZa1Fh2s7Ljtd7jgtg8nINB4X1FCm11w5MfKcKm-SJEnEcvy8VXDd3srw7iD30KYcQVa2VnVbGUKREcU9IEmg"
    kibana_url: "https://logs.sirius.online"
  backend-test.yaml: |-
    name: "Проблема с бекендом в кластере SIRIUS (TEST)"
    type: any
    index: filebeat-*
    filter:
    - query:
        query_string:
          query: "kubernetes.namespace: *-test AND (json.severity:(ERROR OR CRITICAL) OR json.level_name:(ERROR OR CRITICAL))"
    alert:
    - "rob"
    include: ["json.message", "json.data", "kubernetes.labels.app", "_id", "_index"]
    max_query_size: 10
    alert_missing_value: ""
    alert_subject: "**`{0}`**"
    alert_subject_args: ["kubernetes.labels.app"]
    alert_text: |+
        {0}
        ```
        {1}

        {3}
        ```
        **[Подробности здесь](https://logs.sirius.online/app/kibana#/discover?_g=%28refreshInterval:%28pause:!t,value:0%29,time:%28from:now-1d,to:now%29%29&=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28query_string:%28analyze_wildcard:!t,query:'_id:{2}'%29%29%29&_a=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28language:kuery,query:%27_id:%22{2}%22%27%29,sort:!%28!%28'@timestamp',desc%29%29%29)**
    alert_text_args: ["breakline", "json.message", "_id", "json.data"]
    alert_text_type: alert_text_only
    alert: "elastalert_modules.rob.RobAlerter"
    rob_url: "https://rob.sirius.online/message/logs_test_alert"
    rob_token: "eyJhbGciOiJQUzUxMiJ9.eyJlbWFpbCI6ImdpdGxhYkBzaXJpdXMub25saW5lIiwicm9sZXMiOltdLCJtaWRkbGVOYW1lIjoiIiwibGFzdE5hbWUiOiIiLCJmaXJzdE5hbWUiOiIiLCJpZCI6IjAiLCJwYXJlbnRDb2RlIjpudWxsfQ.4wElX1AAbYchLsUUN8DFNJb3THG7XsURqzYpv98hvrGVZaIxQpmjrS8bIVfcgkewRlRyhBoxamxAqsbNMpBj359FgLdHiOCpst-HPM-hSClNyIEdeJYUDQXkKBL4IIkvwZ4etXwzGhubFtD44unZxgEqzcCDc3ShCts7l0OAxa3LvTue_f_JhxpUYSDQn84jnswEUKvcWGpZ5PcleptbvIM7_yG8h9RxulvXxgckDO5wWqRECcJIqfWMR57xI0aeTgZa1Fh2s7Ljtd7jgtg8nINB4X1FCm11w5MfKcKm-SJEnEcvy8VXDd3srw7iD30KYcQVa2VnVbGUKREcU9IEmg"
    kibana_url: "https://logs.sirius.online"
  odyssey-prod.yaml: |-
    name: "Проблема с коннектом к БД в кластере SIRIUS (PROD)"
    type: any
    index: filebeat-*
    filter:
    - query:
        query_string:
          query: "kubernetes.container.name: odyssey AND (kubernetes.namespace: postgres-prod AND json.level: error)"
    alert:
    - "rob"
    include: ["kubernetes.container.name", "json.message", "_id"]
    max_query_size: 1000
    alert_missing_value: ""
    alert_subject: "**`{0}`**"
    alert_subject_args: ["kubernetes.container.name"]
    alert_text: |+
        {0}
        ```
        {1}

        {3}
        ```

        **[Подробности здесь](https://logs.sirius.online/app/kibana#/discover?_g=%28refreshInterval:%28pause:!t,value:0%29,time:%28from:now-1d,to:now%29%29&=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28query_string:%28analyze_wildcard:!t,query:'_id:{2}'%29%29%29&_a=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28language:kuery,query:%27_id:%22{2}%22%27%29,sort:!%28!%28'@timestamp',desc%29%29%29)**
    alert_text_args: ["breakline", "json.message", "_id"]
    alert_text_type: alert_text_only
    alert: "elastalert_modules.rob.RobAlerter"
    rob_url: "https://rob.sirius.online/message/logs_prod_alert"
    rob_token: "eyJhbGciOiJQUzUxMiJ9.eyJlbWFpbCI6ImdpdGxhYkBzaXJpdXMub25saW5lIiwicm9sZXMiOltdLCJtaWRkbGVOYW1lIjoiIiwibGFzdE5hbWUiOiIiLCJmaXJzdE5hbWUiOiIiLCJpZCI6IjAiLCJwYXJlbnRDb2RlIjpudWxsfQ.4wElX1AAbYchLsUUN8DFNJb3THG7XsURqzYpv98hvrGVZaIxQpmjrS8bIVfcgkewRlRyhBoxamxAqsbNMpBj359FgLdHiOCpst-HPM-hSClNyIEdeJYUDQXkKBL4IIkvwZ4etXwzGhubFtD44unZxgEqzcCDc3ShCts7l0OAxa3LvTue_f_JhxpUYSDQn84jnswEUKvcWGpZ5PcleptbvIM7_yG8h9RxulvXxgckDO5wWqRECcJIqfWMR57xI0aeTgZa1Fh2s7Ljtd7jgtg8nINB4X1FCm11w5MfKcKm-SJEnEcvy8VXDd3srw7iD30KYcQVa2VnVbGUKREcU9IEmg"
    kibana_url: "https://logs.sirius.online"
  odyssey-test.yaml: |-
    name: "Проблема с коннектом к БД в кластере SIRIUS (TEST)"
    type: any
    index: filebeat-*
    filter:
    - query:
        query_string:
          query: "kubernetes.container.name: odyssey AND (kubernetes.namespace: postgres-test AND json.level: error)"
    alert:
    - "rob"
    include: ["kubernetes.container.name", "json.message", "_id"]
    max_query_size: 10
    alert_missing_value: ""
    alert_subject: "**`{0}`**"
    alert_subject_args: ["kubernetes.container.name"]
    alert_text: |+
        {0}
        ```
        {1}

        {3}
        ```

        **[Подробности здесь](https://logs.sirius.online/app/kibana#/discover?_g=%28refreshInterval:%28pause:!t,value:0%29,time:%28from:now-1d,to:now%29%29&=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28query_string:%28analyze_wildcard:!t,query:'_id:{2}'%29%29%29&_a=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28language:kuery,query:%27_id:%22{2}%22%27%29,sort:!%28!%28'@timestamp',desc%29%29%29)**
    alert_text_args: ["breakline", "json.message", "_id"]
    alert_text_type: alert_text_only
    alert: "elastalert_modules.rob.RobAlerter"
    rob_url: "https://rob.sirius.online/message/logs_test_alert"
    rob_token: "eyJhbGciOiJQUzUxMiJ9.eyJlbWFpbCI6ImdpdGxhYkBzaXJpdXMub25saW5lIiwicm9sZXMiOltdLCJtaWRkbGVOYW1lIjoiIiwibGFzdE5hbWUiOiIiLCJmaXJzdE5hbWUiOiIiLCJpZCI6IjAiLCJwYXJlbnRDb2RlIjpudWxsfQ.4wElX1AAbYchLsUUN8DFNJb3THG7XsURqzYpv98hvrGVZaIxQpmjrS8bIVfcgkewRlRyhBoxamxAqsbNMpBj359FgLdHiOCpst-HPM-hSClNyIEdeJYUDQXkKBL4IIkvwZ4etXwzGhubFtD44unZxgEqzcCDc3ShCts7l0OAxa3LvTue_f_JhxpUYSDQn84jnswEUKvcWGpZ5PcleptbvIM7_yG8h9RxulvXxgckDO5wWqRECcJIqfWMR57xI0aeTgZa1Fh2s7Ljtd7jgtg8nINB4X1FCm11w5MfKcKm-SJEnEcvy8VXDd3srw7iD30KYcQVa2VnVbGUKREcU9IEmg"
    kibana_url: "https://logs.sirius.online"
  rob-dev.yaml: |-
    name: "Проблема с Робом в кластере SIRIUS (DEV)"
    type: any
    index: filebeat-*
    filter:
    - query:
        query_string:
          query: "kubernetes.container.name : (calendar OR telegram OR tracker) AND (json.severity:(ERROR OR CRITICAL) OR json.level_name:(ERROR OR CRITICAL)) AND kubernetes.namespace: rob-dev"
    alert:
    - "rob"
    include: ["json.message", "json.data", "kubernetes.labels.app", "_id", "_index"]
    max_query_size: 10
    alert_missing_value: ""
    alert_subject: "**`{0}`**"
    alert_subject_args: ["kubernetes.labels.app"]
    alert_text: |+
        {0}
        ```
        {1}

        {3}
        ```

        **[Подробности здесь](https://logs.sirius.online/app/kibana#/discover?_g=%28refreshInterval:%28pause:!t,value:0%29,time:%28from:now-1d,to:now%29%29&=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28query_string:%28analyze_wildcard:!t,query:'_id:{2}'%29%29%29&_a=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28language:kuery,query:%27_id:%22{2}%22%27%29,sort:!%28!%28'@timestamp',desc%29%29%29)**
    alert_text_args: ["breakline", "json.message", "_id", "json.data"]
    alert_text_type: alert_text_only
    alert: "elastalert_modules.rob.RobAlerter"
    rob_url: "https://rob.sirius.online/message/logs_dev_alert"
    rob_token: "eyJhbGciOiJQUzUxMiJ9.eyJlbWFpbCI6ImdpdGxhYkBzaXJpdXMub25saW5lIiwicm9sZXMiOltdLCJtaWRkbGVOYW1lIjoiIiwibGFzdE5hbWUiOiIiLCJmaXJzdE5hbWUiOiIiLCJpZCI6IjAiLCJwYXJlbnRDb2RlIjpudWxsfQ.4wElX1AAbYchLsUUN8DFNJb3THG7XsURqzYpv98hvrGVZaIxQpmjrS8bIVfcgkewRlRyhBoxamxAqsbNMpBj359FgLdHiOCpst-HPM-hSClNyIEdeJYUDQXkKBL4IIkvwZ4etXwzGhubFtD44unZxgEqzcCDc3ShCts7l0OAxa3LvTue_f_JhxpUYSDQn84jnswEUKvcWGpZ5PcleptbvIM7_yG8h9RxulvXxgckDO5wWqRECcJIqfWMR57xI0aeTgZa1Fh2s7Ljtd7jgtg8nINB4X1FCm11w5MfKcKm-SJEnEcvy8VXDd3srw7iD30KYcQVa2VnVbGUKREcU9IEmg"
    kibana_url: "https://logs.sirius.online"
  rob-prod.yaml: |-
    ---
    name: "Проблема с Робом в кластере SIRIUS (PROD)"
    type: any
    index: filebeat-*
    filter:
    - query:
        query_string:
          query: "kubernetes.container.name : (calendar OR telegram OR tracker OR web) AND (json.severity:(ERROR OR CRITICAL) OR json.level_name:(ERROR OR CRITICAL)) AND kubernetes.namespace: rob-prod"
    alert:
    - "rob"
    include: ["json.message", "json.data", "kubernetes.labels.app", "_id", "_index"]
    alert_missing_value: ""
    alert_subject: "**`{0}`**"
    alert_subject_args: ["kubernetes.labels.app"]
    max_query_size: 10
    alert_text: |+
        {0}
        ```
        {1}

        {3}
        ```

        **[Подробности здесь](https://logs.sirius.online/app/kibana#/discover?_g=%28refreshInterval:%28pause:!t,value:0%29,time:%28from:now-1d,to:now%29%29&=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28query_string:%28analyze_wildcard:!t,query:'_id:{2}'%29%29%29&_a=%28columns:!%28_source%29,index:efb38140-f415-11e9-8e35-01a5921e61bf,interval:auto,query:%28language:kuery,query:%27_id:%22{2}%22%27%29,sort:!%28!%28'@timestamp',desc%29%29%29)**
    alert_text_args: ["breakline", "json.message", "_id", "json.data"]
    alert_text_type: alert_text_only
    alert: "elastalert_modules.rob.RobAlerter"
    rob_url: "https://rob.sirius.online/message/logs_prod_alert"
    rob_token: "eyJhbGciOiJQUzUxMiJ9.eyJlbWFpbCI6ImdpdGxhYkBzaXJpdXMub25saW5lIiwicm9sZXMiOltdLCJtaWRkbGVOYW1lIjoiIiwibGFzdE5hbWUiOiIiLCJmaXJzdE5hbWUiOiIiLCJpZCI6IjAiLCJwYXJlbnRDb2RlIjpudWxsfQ.4wElX1AAbYchLsUUN8DFNJb3THG7XsURqzYpv98hvrGVZaIxQpmjrS8bIVfcgkewRlRyhBoxamxAqsbNMpBj359FgLdHiOCpst-HPM-hSClNyIEdeJYUDQXkKBL4IIkvwZ4etXwzGhubFtD44unZxgEqzcCDc3ShCts7l0OAxa3LvTue_f_JhxpUYSDQn84jnswEUKvcWGpZ5PcleptbvIM7_yG8h9RxulvXxgckDO5wWqRECcJIqfWMR57xI0aeTgZa1Fh2s7Ljtd7jgtg8nINB4X1FCm11w5MfKcKm-SJEnEcvy8VXDd3srw7iD30KYcQVa2VnVbGUKREcU9IEmg"
    kibana_url: "https://logs.sirius.online"

config:
  elastalert_config: |-
    ---
    rules_folder: /opt/rules
    max_scrolling_count: 990
    scan_subdirectories: false
    run_every:
      minutes: 1
    buffer_time:
      minutes: 5
    es_host: elasticsearch-master.logging.svc
    es_port: 9200
    writeback_index: elastalert_status
    use_ssl: False
    verify_certs: True
    alert_time_limit:
      minutes: 60