stages:
  - sirius
  - univ

.base-elastalert:
  when: manual
  before_script:
    - echo 'Deploy parameters:'
    - echo 'CLUSTER_NAME =>' ${CLUSTER_NAME}
  script:
    - kubectl get ns logging || kubectl create ns logging
    - chmod +x ./scripts/helm_deploy_and_wait.sh
    - RELEASE_NAME="elastalert-v1"
      NAMESPACE="logging"
      CHART="chart"
      HELM_ARGS="
      -f chart/conf/${CLUSTER_NAME}/values.yaml
      -f chart/conf/${CLUSTER_NAME}/rules.yaml
      -f chart/conf/${CLUSTER_NAME}/config.yaml
      -f chart/conf/${CLUSTER_NAME}/modules.yaml
      --set global.yc_secret="${YC_REGISTRY}"
      --set global.gitlab_secret="${INFRA_REGISTRY}"
      --debug"
      ./scripts/helm_deploy_and_wait.sh

#############  SIRIUS  ############

sirius elastalert prod:
  extends:
    - .base-elastalert
  stage: sirius
  environment:
    name: prod
  variables:
    CLUSTER_NAME: "sirius"
  tags:
    - kube-ci

#############  UNIV  ############

univ elastalert prod:
  extends:
    - .base-elastalert
  stage: univ
  environment:
    name: prod
  variables:
    CLUSTER_NAME: "univ"
  tags:
    - kube-univ