stages:
  - cpm
  - corp
  - univ
  - sirius

.base-elastalert:
  when: manual
  before_script:
    - echo 'Deploy parameters:'
    - echo 'CLUSTER_NAME =>' ${CLUSTER_NAME}
  script:
    - kubectl get ns elastalert || kubectl create ns elastalert
    - chmod +x ./scripts/helm_deploy_and_wait.sh
    - RELEASE_NAME="elastalert-v1"
      NAMESPACE="elastalert"
      CHART="deploy/helm"
      HELM_ARGS="
      -f deploy/helm/conf/${CLUSTER_NAME}/values.yaml
      -f deploy/helm/conf/${CLUSTER_NAME}/rules.yaml
      -f deploy/helm/conf/${CLUSTER_NAME}/config.yaml
      -f deploy/helm/conf/${CLUSTER_NAME}/modules.yaml
      --set global.yc_secret="${YC_REGISTRY}"
      --set global.gitlab_secret="${GITLAB_REGISTRY}"
      --atomic
      --wait"
      ./scripts/helm_deploy_and_wait.sh

#############  CPM-DEV  ############

cpm elastalert stage:
  extends:
    - .base-elastalert
  stage: cpm
  environment:
    name: stage
  variables:
    CLUSTER_NAME: "cpm-dev"
  tags:
    - kube-cpm

#############  CPM-YC  ############

cpm elastalert prod:
  extends:
    - .base-elastalert
  stage: cpm
  environment:
    name: prod
  variables:
    CLUSTER_NAME: "cpm"
  tags:
    - cpm-yac

#############  CORP  ############

corp elastalert prod:
  extends:
    - .base-elastalert
  stage: corp
  environment:
    name: prod
  variables:
    CLUSTER_NAME: "corp"
  tags:
    - kube-corp

#############  UNIV  ############

univ elastalert prod:
  extends:
    - .base-elastalert
  stage: univ
  environment:
    name: prod
  variables:
    CLUSTER_NAME: "univ"
  tags:
    - kube-univ

#############  SIRIUS  ############

sirius elastalert prod:
  extends:
    - .base-elastalert
  stage: sirius
  environment:
    name: prod
  variables:
    CLUSTER_NAME: "sirius"
  tags:
    - kube-ci
