apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "elastalert.fullname" . }}
  labels:
    app: {{ template "elastalert.name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "elastalert.name" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        checksum/rules: {{ include (print $.Template.BasePath "/rules.yaml") . | sha256sum }}
      labels:
        name: {{ template "elastalert.fullname" . }}
        app: {{ template "elastalert.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "elastalert.serviceAccountName" . }}
      containers:
      - name: elastalert
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /opt/config
          name: {{ .Release.Name }}-config
        - mountPath: /opt/rules
          name: {{ .Release.Name }}-rules
        - mountPath: /usr/local/lib/python3.6/site-packages/elastalert_modules
          name: {{ .Release.Name }}-modules
        resources:
{{ toYaml .Values.resources | indent 12 }}
      restartPolicy: Always
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- with .Values.image.pullSecrets }}
      imagePullSecrets:
{{- range . }}
      - name: {{ . }}
{{- end }}
{{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          name: modules
        name: {{ .Release.Name }}-modules
      - configMap:
          defaultMode: 420
          name: rules
        name: {{ .Release.Name }}-rules
      - configMap:
          defaultMode: 420
          items:
          - key: elastalert_config
            path: elastalert_config.yaml
          name: config
        name: {{ .Release.Name }}-config
