apiVersion: v1
data:
  __init__.py: ""
{{- range $key, $value := .Values.modules }}
{{ $key | indent 2}}: |-
{{ $value | indent 4}}
{{- end }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-modules
  labels:
    app: {{ template "elastalert.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
