apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rules
  labels:
    app: {{ template "elastalert.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.rules }}
{{ $key | indent 2}}: |-
{{ $value | indent 4}}
{{- end }}
