configPath: "conf/{{ .Values.global.CLUSTER_NAME }}/config.yaml"

rulesPath: "conf/{{ .Values.global.CLUSTER_NAME }}/rules.yaml"

# number of replicas to run
replicaCount: 1

# number of helm release revisions to retain
revisionHistoryLimit: 5

# Default internal between alert checks against the elasticsearch datasource, in minutes
runIntervalMins: 1

# Default rule buffer duration, in minutes
bufferTimeMins: 15

#The maximum time between queries for ElastAlert to start at the most recently run query. The default is one week.
oldQueryLimitMins: 10080

# Amount of time to retry and deliver failed alerts (1440 minutes per day)
alertRetryLimitMins: 2880

# Default time before realerting, in minutes
realertIntervalMins: ""

writebackIndex: elastalert

image:
  # docker image
  repository: cr.yandex/crpcm9tg75s8gu2hqkp9/elastalert
  # docker image tag
  tag: latest
  pullPolicy: Always
  pullSecrets:
  - sirius-registry

resources: {}

# Annotations to be added to pods
podAnnotations: {}

elasticsearch:
  # elasticsearch endpoint e.g. (svc.namespace||svc)
  host: elasticsearch
  # elasticsearch port
  port: 9200
  # whether or not to connect to es_host using TLS
  useSsl: "False"
  # Username if authenticating to ES with basic auth
  username: ""
  # Password if authenticating to ES with basic auth
  password: ""
  # Specifies an existing secret to be used for the ES username/password
  credentialsSecret: ""
  # The key in elasticsearch.credentialsSecret that stores the ES password
  credentialsSecretUsernameKey: ""
  # The key in elasticsearch.credentialsSecret that stores the ES username
  credentialsSecretPasswordKey: ""
  # whether or not to verify TLS certificates
  verifyCerts: "True"

optEnv: []

extraConfigOptions: {}

rules: {}

config: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityPolicy:
  create: false

nodeSelector: {}

affinity: {}

tolerations: []

extraVolumes: []

extraVolumeMounts: []
